Repository jonataslaw/getx, pull requests merged in 2020-09, with the labels that each got.

#534 [docs] Change "namedRoutes" for "GetPages" in docs
  README-es.md
  README.md
  README.pl.md
  README.pt-br.md
  documentation/en_US/dependency_management.md
  documentation/es_ES/dependency_management.md
  documentation/pt_BR/dependency_management.md
  documentation/pt_BR/route_management.md
  test/routes_test.dart
Labels: documentation, enhancement

#576 new README docs section
  README.md
Labels: documentation

#590 Contribution videos and articles in Readme
  README.md
Labels: documentation

#580 docs(pt-BR): make dependency management docs of pt-br up to date
  documentation/en_US/dependency_management.md
  documentation/pt_BR/dependency_management.md
Labels: documentation

#589 Fix for Get.create() lifecycle
  .gitignore
  lib/src/instance/extension_instance.dart
  lib/src/instance/get_instance.dart
Labels: enhancement

#593 Fixes subscription for Rx::bindStream
  lib/src/state_manager/rx/rx_core/rx_impl.dart
  lib/src/state_manager/rx/rx_iterables/rx_list.dart
  lib/src/state_manager/rx/rx_iterables/rx_map.dart
  lib/src/state_manager/rx/rx_iterables/rx_set.dart
Labels: bug

#603 change `arguments` to dynamic (roadmap)
  lib/src/navigation/extension_navigation.dart
  lib/src/navigation/routes/observers/route_observer.dart
Labels: Suggestion, Waiting for customer response

#612 PrintExtensions
  lib/src/utils/extensions/dynamic_extensions.dart
  lib/src/utils/regex/get_utils.dart
  test/src/extensions/dynamic_extensions_test.dart
Labels: enhancement

#638 Fix #624
  packages/get_utils/lib/src/get_utils/get_utils.dart
Labels: enhancement

#647 Fixes Get.create() and GetWidget()
  packages/get_instance/lib/src/extension_instance.dart
  packages/get_instance/lib/src/get_instance.dart
  packages/get_state_manager/lib/src/simple/get_view.dart
Labels: bug, expected behavior
